## import libaries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import pylab as pl
import scipy.optimize as opt
from sklearn import preprocessing
from sklearn.model_selection import train_test_split

## Reading data from csv file

In [2]:
dataframe = pd.read_csv("fetal_health.csv")
dataframe.head()

baseline value  accelerations  fetal_movement  uterine_contractions  \
0           120.0          0.000             0.0                 0.000   
1           132.0          0.006             0.0                 0.006   
2           133.0          0.003             0.0                 0.008   
3           134.0          0.003             0.0                 0.008   
4           132.0          0.007             0.0                 0.008   

   light_decelerations  severe_decelerations  prolongued_decelerations  \
0                0.000                   0.0                       0.0   
1                0.003                   0.0                       0.0   
2                0.003                   0.0                       0.0   
3                0.003                   0.0                       0.0   
4                0.000                   0.0                       0.0   

   abnormal_short_term_variability  mean_value_of_short_term_variability  \
0                             73.0                                   0.5   
1                             17.0                                   2.1   
2                             16.0                                   2.1   
3                             16.0                                   2.4   
4                             16.0                                   2.4   

   percentage_of_time_with_abnormal_long_term_variability  ...  histogram_min  \
0                                               43.0       ...           62.0   
1                                                0.0       ...           68.0   
2                                                0.0       ...           68.0   
3                                                0.0       ...           53.0   
4                                                0.0       ...           53.0   

   histogram_max  histogram_number_of_peaks  histogram_number_of_zeroes  \
0          126.0                        2.0                         0.0   
1          198.0                        6.0                         1.0   
2          198.0                        5.0                         1.0   
3          170.0                       11.0                         0.0   
4          170.0                        9.0                         0.0   

   histogram_mode  histogram_mean  histogram_median  histogram_variance  \
0           120.0           137.0             121.0                73.0   
1           141.0           136.0             140.0                12.0   
2           141.0           135.0             138.0                13.0   
3           137.0           134.0             137.0                13.0   
4           137.0           136.0             138.0                11.0   

   histogram_tendency  fetal_health  
0                 1.0           2.0  
1                 0.0           1.0  
2                 0.0           1.0  
3                 1.0           1.0  
4                 1.0           1.0  

[5 rows x 22 columns]

In [3]:
dataframe.describe()

baseline value  accelerations  fetal_movement  uterine_contractions  \
count     2126.000000    2126.000000     2126.000000           2126.000000   
mean       133.303857       0.003178        0.009481              0.004366   
std          9.840844       0.003866        0.046666              0.002946   
min        106.000000       0.000000        0.000000              0.000000   
25%        126.000000       0.000000        0.000000              0.002000   
50%        133.000000       0.002000        0.000000              0.004000   
75%        140.000000       0.006000        0.003000              0.007000   
max        160.000000       0.019000        0.481000              0.015000   

       light_decelerations  severe_decelerations  prolongued_decelerations  \
count          2126.000000           2126.000000               2126.000000   
mean              0.001889              0.000003                  0.000159   
std               0.002960              0.000057                  0.000590   
min               0.000000              0.000000                  0.000000   
25%               0.000000              0.000000                  0.000000   
50%               0.000000              0.000000                  0.000000   
75%               0.003000              0.000000                  0.000000   
max               0.015000              0.001000                  0.005000   

       abnormal_short_term_variability  mean_value_of_short_term_variability  \
count                      2126.000000                           2126.000000   
mean                         46.990122                              1.332785   
std                          17.192814                              0.883241   
min                          12.000000                              0.200000   
25%                          32.000000                              0.700000   
50%                          49.000000                              1.200000   
75%                          61.000000                              1.700000   
max                          87.000000                              7.000000   

       percentage_of_time_with_abnormal_long_term_variability  ...  \
count                                         2126.00000       ...   
mean                                             9.84666       ...   
std                                             18.39688       ...   
min                                              0.00000       ...   
25%                                              0.00000       ...   
50%                                              0.00000       ...   
75%                                             11.00000       ...   
max                                             91.00000       ...   

       histogram_min  histogram_max  histogram_number_of_peaks  \
count    2126.000000    2126.000000                2126.000000   
mean       93.579492     164.025400                   4.068203   
std        29.560212      17.944183                   2.949386   
min        50.000000     122.000000                   0.000000   
25%        67.000000     152.000000                   2.000000   
50%        93.000000     162.000000                   3.000000   
75%       120.000000     174.000000                   6.000000   
max       159.000000     238.000000                  18.000000   

       histogram_number_of_zeroes  histogram_mode  histogram_mean  \
count                 2126.000000     2126.000000     2126.000000   
mean                     0.323612      137.452023      134.610536   
std                      0.706059       16.381289       15.593596   
min                      0.000000       60.000000       73.000000   
25%                      0.000000      129.000000      125.000000   
50%                      0.000000      139.000000      136.000000   
75%                      0.000000      148.000000      145.000000   
max                     10.000000      187.000000      182.000000   

       histogram_median  histogr

### Data pre-processing and selection

In [4]:
dataframe.dtypes

baseline value                                            float64
accelerations                                             float64
fetal_movement                                            float64
uterine_contractions                                      float64
light_decelerations                                       float64
severe_decelerations                                      float64
prolongued_decelerations                                  float64
abnormal_short_term_variability                           float64
mean_value_of_short_term_variability                      float64
percentage_of_time_with_abnormal_long_term_variability    float64
mean_value_of_long_term_variability                       float64
histogram_width                                           float64
histogram_min                                             float64
histogram_max                                             float64
histogram_number_of_peaks                                 float64
histogram_

In [5]:
x = np.asarray(dataframe[[
    'baseline value',
    'accelerations',
    'fetal_movement',
    'uterine_contractions',
    'light_decelerations',
    'severe_decelerations',
    'prolongued_decelerations',
    'abnormal_short_term_variability',
    'mean_value_of_short_term_variability',
    'percentage_of_time_with_abnormal_long_term_variability',
    'mean_value_of_long_term_variability',
    'histogram_width',
    'histogram_min',
    'histogram_max',
    'histogram_number_of_peaks',
    'histogram_number_of_zeroes',
    'histogram_mode',
    'histogram_mean',
    'histogram_median',
    'histogram_variance',
    'histogram_tendency'
]])
x[0:5]

array([[1.20e+02, 0.00e+00, 0.00e+00, 0.00e+00, 0.00e+00, 0.00e+00,
        0.00e+00, 7.30e+01, 5.00e-01, 4.30e+01, 2.40e+00, 6.40e+01,
        6.20e+01, 1.26e+02, 2.00e+00, 0.00e+00, 1.20e+02, 1.37e+02,
        1.21e+02, 7.30e+01, 1.00e+00],
       [1.32e+02, 6.00e-03, 0.00e+00, 6.00e-03, 3.00e-03, 0.00e+00,
        0.00e+00, 1.70e+01, 2.10e+00, 0.00e+00, 1.04e+01, 1.30e+02,
        6.80e+01, 1.98e+02, 6.00e+00, 1.00e+00, 1.41e+02, 1.36e+02,
        1.40e+02, 1.20e+01, 0.00e+00],
       [1.33e+02, 3.00e-03, 0.00e+00, 8.00e-03, 3.00e-03, 0.00e+00,
        0.00e+00, 1.60e+01, 2.10e+00, 0.00e+00, 1.34e+01, 1.30e+02,
        6.80e+01, 1.98e+02, 5.00e+00, 1.00e+00, 1.41e+02, 1.35e+02,
        1.38e+02, 1.30e+01, 0.00e+00],
       [1.34e+02, 3.00e-03, 0.00e+00, 8.00e-03, 3.00e-03, 0.00e+00,
        0.00e+00, 1.60e+01, 2.40e+00, 0.00e+00, 2.30e+01, 1.17e+02,
        5.30e+01, 1.70e+02, 1.10e+01, 0.00e+00, 1.37e+02, 1.34e+02,
        1.37e+02, 1.30e+01, 1.00e+00],
       [1.32e+02, 7.00e-03, 

In [6]:
y = np.asarray(dataframe['fetal_health'])
y [0:5]

array([2., 1., 1., 1., 1.])

### Train and Test data

In [7]:
x_train, x_test, y_train, y_test = train_test_split( x, y, test_size=0.2, random_state=4)
print ('Train set:', x_train.shape,  y_train.shape)
print ('Test set:', x_test.shape,  y_test.shape)

Train set: (1700, 21) (1700,)
Test set: (426, 21) (426,)


In [8]:
np.unique(y_test)

array([1., 2., 3.])

## Modeling: Support Vector Machine

In [9]:
from sklearn import svm
clf = svm.SVC(kernel='linear', probability = True, C = 1, gamma = 'scale')
clf.fit(x_train, y_train)

SVC(C=1, kernel='linear', probability=True)

In [10]:
yhat = clf.predict(x_test)
yhat [0:5]

array([1., 1., 1., 1., 1.])

### Evaluation

In [11]:
from sklearn.metrics import classification_report, confusion_matrix
import itertools

In [12]:
from sklearn.metrics import confusion_matrix, classification_report
import numpy as np

# Your code to generate y_test and yhat

# Get the unique labels present in y_test
unique_labels = np.unique(y_test)

# Check if there are at least two unique labels
if len(unique_labels) >= 2:
    cnf_matrix = confusion_matrix(y_test, yhat, labels=unique_labels)
    np.set_printoptions(precision=2)
    print(classification_report(y_test, yhat))
else:
    print("There are not enough unique labels in y_test to compute a confusion matrix.")

              precision    recall  f1-score   support

         1.0       0.92      0.94      0.93       334
         2.0       0.65      0.63      0.64        62
         3.0       0.83      0.67      0.74        30

    accuracy                           0.88       426
   macro avg       0.80      0.75      0.77       426
weighted avg       0.88      0.88      0.88       426



## Modeling: Decision Tress

In [13]:
from sklearn.tree import DecisionTreeClassifier
drugTree = DecisionTreeClassifier(criterion="gini")
drugTree

DecisionTreeClassifier()

In [14]:
drugTree.fit(x_train, y_train)

DecisionTreeClassifier()

### Prediction

In [15]:
predTree = drugTree.predict(x_test)

In [16]:
print (predTree [0:5])
print (y_test [0:5])

[3. 2. 1. 2. 1.]
[3. 2. 1. 1. 1.]


### Evaluation

In [17]:
from sklearn import metrics
print (print("DecisionTrees's Accuracy: ", metrics.accuracy_score(y_test, predTree)))

DecisionTrees's Accuracy:  0.931924882629108
None
